### ISSUE TITLE
How can we use in mT5

### ISSUE THREAD

**Issue by sainathpawar** [Ki6an/fastT5#20]
Can we use this library for mT5 ? if yes what modification do we require?

**Comment by JulesBelveze** [comment]
I am actually trying to use it with `csebuetnlp/mT5_multilingual_XLSum` and facing the following error message:
```
TypeError: forward() got an unexpected keyword argument 'cross_attn_head_mask'
```

**Comment by JulesBelveze** [comment]
@sainathpawar I actually tried with a mT5 model and it worked fine in my case 😺
