### ISSUE TITLE
How to use numpy inputs?

### ISSUE THREAD

**Issue by Anku5hk** [Ki6an/fastT5#22]
Is it possible to use numpy inputs with fastt5 ONNX model? Is someone working on this?

**Comment by Ki6an** [comment]
onnx models only use NumPy inputs. in fastt5 the inputs to  `onnruntime` session `run` function we feed input as numpy arrays after converting them from torch tensors.

https://github.com/Ki6an/fastT5/blob/721b005cf7566252de73746a52147b356339b905/fastT5/onnx_models.py#L67
