### ISSUE TITLE
Error from export_and_get_onnx_model() 

### ISSUE THREAD

**Issue by PhaneendraGunda** [Ki6an/fastT5#24]
Hi,

I am getting the following error when I run the following test snippet provided in the readme.md file. But I can see 3 onnx files are created one for encoder, one for decoder and one for init decoder. 

**Environment**
fastT5 - 0.0.7
MacOS - Big Sur (11.2.3)
Python conda - 3.7.6 

**Error**
_Exporting to onnx... |################################| 3/3
[libprotobuf ERROR google/protobuf/descriptor_database.cc:394] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL google/protobuf/descriptor.cc:1356] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):_ 

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Test code snippet**

```
from fastT5 import export_and_get_onnx_model
from transformers import AutoTokenizer

model_name = 't5-small'
model = export_and_get_onnx_model(model_name)

tokenizer = AutoTokenizer.from_pretrained(model_name)
t_input = "translate English to French: The universe is a dark forest."
token = tokenizer(t_input, return_tensors='pt')

tokens = model.generate(input_ids=token['input_ids'],
                        attention_mask=token['attention_mask'],
                        num_beams=2)

output = tokenizer.decode(tokens.squeeze(), skip_special_tokens=True)
print(output)
```

**Comment by Ki6an** [comment]
The latest version of onnx (i.e  `onnx v1.10.1`) is causing the issue. downgrade it to `v1.10.0` and try again.

**Comment by PhaneendraGunda** [comment]
Yes, the old version was installed on my Mac. I think it was 1.7.0. But
anyway i had to upgrade both onnx and protobuf libraries. Thank you
once again for your help.


Thanks,
Phaneendra
