### ISSUE TITLE
ONNX Runtime Session Defaults Discrepancy

### ISSUE THREAD

**Issue by sam-writer** [Ki6an/fastT5#25]
In the definition of `get_onnx_runtime_sessions`, we have `n_threads: int = 4,`. In the docstring, it says `n_threads (int) :  Sets the number of threads used to parallelize the execution within nodes. Default is 0 to let onnxruntime choose`

Is there a reason that `n_threads` defaults to 4?

**Comment by Ki6an** [comment]
sorry for the late response, 

if we set it to `0`, we let `onnxruntime` choose the number of threads.
while testing, I found in some cases I got good results with `n_threads=4`. you can experiment with this number if you get better results keep it or you can let onnxruntime choose.
