### ISSUE TITLE
get_onnx_model fails

### ISSUE THREAD

**Issue by WarrierRajeev** [Ki6an/fastT5#28]
When a custom models folder is given in `model_name_or_path`, it fails to find the model files.

Reason:
```
get_model_paths(
        model_name_or_path, saved_models_path, quantized
    )
```
is used to get the model paths where the `saved_model_path` is imported (not derived from the `model_name_or_path`) and is equal to `./models/` and so it checks if the files exist inside the current dir's models folder only.

**Comment by deepaksinghtopwal** [comment]
Yeah , i am having the similar issue, where i can export the quantized model, but unable to load and get the "uantized model don't exist in the model folder, first quantize the model!" error.
