### ISSUE TITLE
Error with "kiri-ai/t5-base-qa-summary-emotion" model

### ISSUE THREAD

**Issue by orendar** [Ki6an/fastT5#3]
Hey,

If I understand correctly, then this library should work with all t5 models including finetuned ones right? When I try to generate onnx representation of model "kiri-ai/t5-base-qa-summary-emotion", I get the following error:
`File "C:\Users\Oren\Anaconda3\envs\emotion-qa\lib\site-packages\transformers\models\t5\modeling_t5.py", line 499, in forward
    scores += position_bias
RuntimeError: output with shape [5, 12, 1, 2] doesn't match the broadcast shape [5, 12, 2, 2]`

**Comment by Ki6an** [comment]
the issue has been addressed before [here](https://github.com/Ki6an/fastT5/issues/1), I've posted a fix for it there.

**Comment by orendar** [comment]
Thanks - you might want to keep that issue open / pin it until the PR is merged so that people will be able to see it :)
