### ISSUE TITLE
Errors when loading saved onnx files

### ISSUE THREAD

**Issue by itaim** [Ki6an/fastT5#33]
We have an issue with saving and loading `onnx` files.
When passing the generated `quant_model_paths` to `get_onnx_runtime_sessions` everything works okay but if I save the file and then run `get_onnx_runtime_sessions` on the loaded quantized files the model throws an error:
```
File "/Users/itai/Code/email-cleaner/.venv/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 184, in run
    raise ValueError("Model requires {} inputs. Input Feed contains {}".format(num_required_inputs, num_inputs))
ValueError: Model requires 3 inputs. Input Feed contains 2
```
This doesn't seem to happen on SageMaker but it happens on mac and also on linux containerized environment.

**Comment by Ki6an** [comment]
what's your `onnxruntime` version and does the `models` folder have all the 3 quantized models?

**Comment by itaim** [comment]
The models folder has the 3 quantized model files. I am not sure what is my `onnxruntime` version. How can I find it?

**Comment by Ki6an** [comment]
`pip3 show onnxruntime` 
 if you are using the latest version of fastt5 you should have `onnxruntime v1.7.0`

**Comment by itaim** [comment]
```
Name: onnxruntime
Version: 1.7.0
Summary: ONNX Runtime is a runtime accelerator for Machine Learning models
Home-page: https://onnxruntime.ai
Author: Microsoft Corporation
Author-email: onnxruntime@microsoft.com
License: MIT License
Location: /Users/itaimarks/Code/email-cleaner/.venv/lib/python3.7/site-packages
Requires: numpy, protobuf
Required-by: fastt5

```

**Comment by Ki6an** [comment]
can you provide the reproducible code? also, are you running it on a docker containerized environment?

**Comment by itaim** [comment]
Yes running in containerized environment, and generating the `onnx` files in the `Dockerfile`.

```
from fastT5 import (
    generate_onnx_representation,
    quantize,
)
import shutil
import os


model_path = "models/email_cleaner"
onnx_model_paths = generate_onnx_representation(model_path)
quant_model_paths = quantize(onnx_model_paths)
print(quant_model_paths)
for file in quant_model_paths:
    shutil.move(file, model_path + "/" + os.path.basename(file))

for file in onnx_model_paths:
    os.remove(file)

```


```
def init_cleaner_model(model_path):
    try:
        start = time.time()
        app.logger.info(f"Loading Cleaner T5 model from: {model_path}")
        tokenizer = AutoTokenizer.from_pretrained(model_path)
        os = platform.platform()
        if os.startswith("Darwin"):
            app.logger.info(f"OS: {os}, Using vanilla T5 model")
            model = T5ForConditionalGeneration.from_pretrained(model_path)
        else:
            app.logger.info(f"OS: {os}, Using FastT5 model")
            quant_model_paths = glob.glob(model_path + "/*-quantized.onnx")
            model_sessions = get_onnx_runtime_sessions(quant_model_paths)
            model = OnnxT5(model_path, model_sessions)

        app.logger.info(
            f"Loading cleaner model and tokenizer took {time.time() - start} seconds"
        )
        return model, tokenizer
    except Exception as ex:
        app.logger.error(ex, exc_info=True)
        return None
```

**Comment by Ki6an** [comment]
I tried fastt5 on a Linux container for simple GQ rest API with flask, and it worked fine. I've linked the [drive files ](https://drive.google.com/file/d/1Tu-NuXZXiO25h9MH_1SNbxKNn0fXtLpq/view?usp=sharing)for the project you can take a look if you are interested.  meanwhile, I'll look into your code.

**Comment by Ki6an** [comment]
I think the order of  `quantized models` has changed while using `glob.glob()` to get the model path. You might be feeding only 2 inputs (of encoder) to init decoder (it needs 3 input [values](https://github.com/Ki6an/fastT5/blob/30887ce857c2292cf48d88b90f5a749dc87d711c/fastT5/onnx_models.py#L66)).

Make sure to provide the quantized models path in [this](https://github.com/Ki6an/fastT5/blob/30887ce857c2292cf48d88b90f5a749dc87d711c/fastT5/ort_settings.py#L48) order to  `get_onnx_runtime_sessions`.

LMK if this solves your issue.

**Comment by itaim** [comment]
Yes it does! Thank you very much!

**Comment by sidsharma72** [comment]
I was facing the same issue - the resolution lies in the order of the quantized model paths.
It should be encoder, decoder, init-decoder.
