### ISSUE TITLE
Incompatible with transformers>=4.16

### ISSUE THREAD

**Issue by nbroad1881** [Ki6an/fastT5#40]
`GenerationMixin` was modified in 4.16 so now it checks for `self.encoder.main_input_name` but the fastT5 encoder does not have that attribute. I believe there are more errors too if you get past this one but I didn't have time to fully explore it.

This commit is where the change happened: https://github.com/huggingface/transformers/commit/fe4197ab11c4cea38a84b8d8a88122b3af7eddd6#diff-b7601d397d5d60326ce61a9c91beaa2afa026014141052b32b07e1d044fbbe17R373

**Comment by piegu** [comment]
Hi @nbroad1881,

You're right. 

I asked @Ki6an on the Hugging Face forum if an update is coming and I published in the same [post](https://discuss.huggingface.co/t/speeding-up-t5-inference/1841/16) a how-to guide that lets you use the latest version of fastT5 with transformers 4.15.0 (better than nothing).
