### ISSUE TITLE
GPU support for fastT5

### ISSUE THREAD

**Issue by rupeshpoojary97** [Ki6an/fastT5#42]
You have used onnxruntime which is CPU compatible but are we looking forward to have onnxruntime-gpu?

**Comment by Ki6an** [comment]
I'm currently working on GPU support, there are a few issues, one of which is adding support for both onnxruntime (CPU) and onnxruntime-GPU in a single library and GPU also does not support quantization. hopefully, onnxruntime adds support for quantization for GPU soon.

**Comment by gennarovaccaro** [comment]
@Ki6an In the meantime, is there any way to improve the inference times of a T5 on GPU?

**Comment by Ki6an** [comment]
@gennarovaccaro follow this thread https://github.com/Ki6an/fastT5/issues/34 it'll give you a basic idea
