### ISSUE TITLE
Conversion of decoder with past_key_values to float16.

### ISSUE THREAD

**Issue by VikasOjha666** [Ki6an/fastT5#50]
Hi @Ki6an. With the converted ONNX model generated. I was trying to convert the decoder_init and decoder to float16. I did the quantization with onnxruntime's transformer optimizer. I was able to convert the decoder_init to fp16 but while converting the decoder with past_key_values I am getting following issue:

AssertionError                            Traceback (most recent call last)
[<ipython-input-10-42606fa3cf84>](https://localhost:8080/#) in <module>()
     25     ,
     26     )
---> 27 optimized_model.convert_float_to_float16()  # FP32 -> FP16
     28 optimized_model.save_model_to_file('/content/optimized_models/t5-base-qa-qg-hl-decoder.onnx')
     29 

6 frames
[/usr/local/lib/python3.7/dist-packages/onnxruntime/transformers/../tools/symbolic_shape_infer.py](https://localhost:8080/#) in _add_suggested_merge(self, symbols, apply)
    216 
    217     def _add_suggested_merge(self, symbols, apply=False):
--> 218         assert all([(type(s) == str and s in self.symbolic_dims_) or is_literal(s) for s in symbols])
    219         symbols = set(symbols)
    220         for k, v in self.suggested_merge_.items():

AssertionError:

Code used:
from onnxruntime.transformers import optimizer

#Decoder.
optimized_model =optimizer.optimize_model(
        input='/content/models/t5-base-qa-qg-hl-decoder.onnx',
        use_gpu=True,
        opt_level=1, only_onnxruntime= True
    ,
    )
optimized_model.convert_float_to_float16()  # FP32 -> FP16
optimized_model.save_model_to_file('/content/optimized_models/t5-base-qa-qg-hl-decoder.onnx')

**Comment by VikasOjha666** [comment]
The issue was solved changing  the line optimized_model.convert_float_to_float16() to optimized_model.convert_float_to_float16(use_symbolic_shape_infer=False)

**Comment by VikasOjha666** [comment]
@Ki6an 
Sorry to revive this issue again. But when I am doing prediction using the above decoder I am getting this issue:

RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Cast node. Name:'graph_input_cast5' Status Message: /onnxruntime_src/onnxruntime/core/framework/op_kernel.cc:78 OrtValue* onnxruntime::OpKernelContext::OutputMLValue(int, const onnxruntime::TensorShape&) status.IsOK() was false. Shape mismatch attempting to re-use buffer. {4,12,1,64} != {4,12,163,64}. Validate usage of dim_value (values should be > 0) and dim_param (all values with the same string should equate to the same size) in shapes in the model.

**Comment by VikasOjha666** [comment]
@Ki6an 
The same issue was coming in the fp16 version of decoder_init . But setting use_symbolic_shape_infer=False did solved this issue in decoder init. But I am already doing the same for decoder and I am getting this issue. Could you please suggest any fix?

**Comment by Ki6an** [comment]
@VikasOjha666  try exporting the decoders to onnx with output names.

**Comment by VikasOjha666** [comment]
@Ki6an I am using the fastT5 model for exporting the ONNX does it do it?
