### ISSUE TITLE
Failed to create CUDAExecutionProvider

### ISSUE THREAD

**Issue by ekaterinatretyak** [Ki6an/fastT5#53]
Hi,

After having obtained ONNX models (not quantized), I would like to run inference on GPU devices with setting onnx runtime:

`model_sessions = get_onnx_runtime_sessions(model_paths, default=False, provider=['CUDAExecutionProvider'])`

However, I get the following error: 

_Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met._

I checked that all dependencies are installed. 
How could I fix it? Thanks in advance for answer

**Comment by Ki6an** [comment]
make sure to uninstall `onnxruntime` and install the right version of `onnxruntime-gpu` depending on the [cuda and cudnn versions](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements) available on your device
