### ISSUE TITLE
Support for py3.10

### ISSUE THREAD

**Issue by adityay121** [Ki6an/fastT5#55]
Hello I just wanted to ask if python 3.10 is supported yet, I have an ubuntu server with the latest LTS release and there are conflicts with the pip packages, log file of the stack trace has been attached, this happen when I try to run `pip install -q transformers fastT5`
Are the latest python versions supported? 
[trace.log](https://github.com/Ki6an/fastT5/files/8624920/trace.log)

**Comment by Ki6an** [comment]
apparently `onnxruntime` does not support for `python 3.10` yet. please read this [comment](https://github.com/Microsoft/onnxruntime/issues/250#issuecomment-1082442830)
