### ISSUE TITLE
Thank You and Demo Running in the Browser

### ISSUE THREAD

**Issue by praeclarum** [Ki6an/fastT5#60]
I just wanted to thank you for this library. I learned a lot from it and will be using it my own projects.

I was able to use it to create an end-to-end pipeline ([transformers-js](https://github.com/praeclarum/transformers-js)) to run T5 in the browser. I think it's pretty cool and wanted to show you: https://transformers-js.praeclarum.org

Thanks again!

**Comment by Ki6an** [comment]
Glad it was helpful. The page looks awesome.

**Comment by praeclarum** [comment]
Glad you got to see it. I’ll close this so it’s not taking up space.
