### ISSUE TITLE
can quantized onnx t5 run on GPU

### ISSUE THREAD

**Issue by gyin-ai** [Ki6an/fastT5#8]
Just wonder whether this quantized onnx t5 can run on GPU.

**Comment by Ki6an** [comment]
unfortunately no. quantized onnx models can only be run on CPU & `onnxruntime-gpu` does not support quantization. 
if you want more details on this question you should create an issue in [onnxruntime](https://github.com/microsoft/onnxruntime).

**Comment by mblank5** [comment]
@Ki6an HI, do we support onnxruntime-gpu mode with V100 or T4 if dont use the quantization?

i see with onnxruntime only we can have x2 speedup ?

**Comment by Ki6an** [comment]
@mblank5 no, this library uses onnxruntime, and to support GPUs you need to have `onnxruntime-GPU` installed.  

BUT you can uninstall `onnxruntime` after the fastt5 library is installed, and install `onnxruntime-gpu` and try running the model but not sure you'll get speed up. for more info refer to [this issue.](https://github.com/Ki6an/fastT5/issues/34)

with `onnxruntime`, you'll get speed up if you are using modern CPUs and more CPU cores.  refer [benchmark ](https://github.com/Ki6an/fastT5#benchmarks)section of README.
