### ISSUE TITLE
Problems with T5 & onnxruntime

### ISSUE THREAD

**Issue by IVannarI** [Ki6an/fastT5#9]
Hello there.
My purpose is to speed up a T5-small (fine-tuned) both on CPU and GPU. 
So, I am trying to transform the net through fastT5. However, using the quantized model on CPU, I get similar performances with respect to the initial model (T5-small, on CPU), without any significant improvement. Am I missing something?

Moreover, I have problems with onnxruntime-gpu. I have read from the other issues that I can't use onnxruntime-gpu with quantization, is that correct? 

Also, I am trying to transform the T5-small model into a non-quantized onnx model, in order to be able to use it on the GPU with onnxruntime-gpu, to obtain some improvements. In this case, i get the errors:  

`[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'Add_98' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:487 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 14 by 16`

or

`[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Add node. Name:'Add_98' Status Message: Add_98: right operand cannot broadcast on dim 2 LeftShape: {1,8,85,85}, RightShape: {1,8,14,85}`

The code is reported below. It fails in the generate method when I try to run it with onnxruntime-gpu. 
```
    t_input = 'translate {} to SQL: '.format(languages[lang]) + original_text
    tokenizer = AutoTokenizer.from_pretrained(model_directory)
    token = tokenizer(t_input, return_tensors='pt')
    tokens = model.generate(input_ids=token['input_ids'], attention_mask=token['attention_mask'], num_beams=3)
```

Thank you.

**Comment by Ki6an** [comment]
can you provide your device specifications? 

>I have read from the other issues that I can't use onnxruntime-gpu with quantization, is that correct?

yes, fastT5 does not support GPU yet both for quantized and non-quantized.

Not sure why you're getting that error but here's a [notebook](https://colab.research.google.com/drive/1j1A3jgWjtoU7f_IhUBAvAb5CMnwcqZih?usp=sharing), it exports t5 to onnx on 
`onnxrunitme-gpu` successfully. 
>the notebook only shows how to export t5 to onnx.

Currently PyTorch models perform faster than onnx models on `gpu`.  the fastt5 script is optimized only for the CPU. To gain the speed over the PyTorch model we need to implement [iobinding.](https://www.onnxruntime.ai/python/api_summary.html#iobinding)

**Comment by VaccaroG** [comment]
Thank you for your answer.
I tried the code in the notebook, and it works for the standard(code-downloaded) t5-small. Moreover, when I use my finetuned t5-small, I get the following error:

`[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Add node. Name:'Add_98' Status Message: Add_98: right operand cannot broadcast on dim 2 LeftShape: {1,8,16,16}, RightShape: {1,8,14,16}`

This is the folder that I use as "model_name":

![image](https://user-images.githubusercontent.com/82599723/114988018-23552e00-9e96-11eb-92a3-c497914a0d50.png)

> can you provide your device specifications and reproducible code?

The code is in this [notebook](https://drive.google.com/file/d/1Wh0cTGKidcXKItBP8gtXUZbW9Gaz29-f/view?usp=sharing)
In this notebook you can see also an unexpected error that raises using the CPU. 
Could it be an issue related to my finetuned t5-small? 

Thank you.

**Comment by AnkitaTW** [comment]
Hi, 
I used the [notebook](https://drive.google.com/file/d/1Wh0cTGKidcXKItBP8gtXUZbW9Gaz29-f/view?usp=sharing) from the above post on a CPU machine.

Did any of you face an error like below?
(I have pasted only the top few and last few lines, please let me know if more information is needed)


> RuntimeError                              Traceback (most recent call last)
> <ipython-input-6-711ff437c21d> in <module>
> ----> 1 model = export_and_get_onnx_model(model_dir,False)
> 
> ~/opt/anaconda3/lib/python3.7/site-packages/fastT5/onnx_models.py in export_and_get_onnx_model(model_or_model_path, quantized)
>     193 
>     194     # Step 1. convert huggingfaces t5 model to onnx
> --> 195     onnx_model_paths = generate_onnx_representation(model_or_model_path)
>     196 
>     197     if quantized:
> 
> ~/opt/anaconda3/lib/python3.7/site-packages/fastT5/onnx_exporter.py in generate_onnx_representation(pretrained_version, model)
>     173             input_names=decoder_input_names,
>     174             output_names=decoder_output_names,
> --> 175             dynamic_axes=dyn_axis_params,
>     176         )
>     177         bar.next()

 ............
> ~/opt/anaconda3/lib/python3.7/site-packages/transformers/models/t5/modeling_t5.py in forward(self, hidden_states, mask, key_value_states, position_bias, past_key_value, layer_head_mask, query_length, use_cache, output_attentions)
>     495                 position_bias = position_bias + mask  # (batch_size, n_heads, seq_length, key_length)
>     496 
> --> 497         scores += position_bias
>     498         attn_weights = F.softmax(scores.float(), dim=-1).type_as(
>     499             scores
> 
> RuntimeError: output with shape [5, 8, 1, 2] doesn't match the broadcast shape [5, 8, 2, 2]

Code block where I get the error:
`model = export_and_get_onnx_model(model_dir,False)`

Please share if there is a way to resolve this/ if I missed something obvious.

**Comment by Ki6an** [comment]
@AnkitaTW see https://github.com/Ki6an/fastT5/issues/1
